---
- hosts: localhost
  roles:
    - ../roles/create_ec2_group

- hosts: ec2_group
  become: yes
  become_user: root
  roles:
    - ../roles/prepare_docker_vars
    - ../roles/update_ec2_hosts
    - ../roles/install_docker
    - ../roles/start_zookeeper
    - ../roles/start_kafka